stateDiagram-v2
    state is_empty <<choice>>
    state is_station_pause <<choice>>
    [*] --> IsEmpty
    IsEmpty --> is_empty
    is_empty --> Empty : root.connections = 0
    Empty --> [*]
    is_empty --> NotEmpty : root.connections > 0
    state NotEmpty {
        [*] --> Paused
        Paused --> Playing : Play()
        Playing --> Paused : Pause()
        Playing --> Stationed : Station time is up
        state Stationed {
            [*] --> is_station_pause
            is_station_pause --> StationedPause : Station.WillPause()
            is_station_pause --> StationedPlay : Not Station.WillPause()
            StationedPause --> Travelling : Travel(thread)
            StationedPlay --> Travelling : Travel(thread)
            Travelling --> [*]
        }

        Stationed --> Playing : Travelled
    }
